spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: your-password
    url: your-url
    username: your-username
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
